config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users,
  						path: '',
  						path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  						controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :playlists, only: [:show, :new, :create, :destroy]
  resources :tags, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]

  get 'search', to: 'pages#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :playlist
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :tags, dependent: :destroy
  accepts_nested_attributes_for :tags
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user, dependent: :destroy

  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :playlist, optional: true

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :current_password
  has_many :playlists, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_playlists, through: :favorites, source: :playlist, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         # :confirmable,
         :omniauthable

  validates :name, presence: true, length: { maximum: 50 }

  def add_favorite(playlist)
    favorite_playlists << playlist
  end

  def delete_favorite(playlist)
    favorites.find_by(playlist_id: playlist.id).destroy
  end

  def favorite?(playlist)
    favorite_playlists.include?(playlist)
  end

  def self.from_omniauth(auth)
  	user = User.where(email: auth.info.email).first
  	if user
      user
  	else
			where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email.nil? ? auth.provider + auth.uid + "@login.function" : auth.info.email
		    user.password = Devise.friendly_token[0,20]
		    user.name = auth.info.name
		    user.image = auth.info.image
		    user.uid = auth.uid
		    user.provider = auth.provider

		    # If you are using confirmable and the provider(s) you use validate emails,
		    # uncomment the line below to skip the confirmation emails.
		    # user.skip_confirmation!
		  end
  	end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    puts params
    puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

    @playlist = Playlist.find(params[:playlist_id])
    current_user.add_favorite(@playlist)
    respond_to :js
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    current_user.delete_favorite(@playlist)
    respond_to :js
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  PER = 9

  def home
    @playlists = Playlist.page(params[:page]).per(PER).order("created_at DESC")
  end

  def search
    if params[:search].present? && params[:search].strip != ""
      playlists = Playlist.find_by_sql("SELECT * FROM playlists where exists ( select  1 from tags where tags.playlist_id = playlists.id and tags.content LIKE '%#{params[:search]}%' order by created_at desc)")
      @playlists = Kaminari.paginate_array(playlists).page(params[:page]).per(PER)
    else
      @playlists = Playlist.page(params[:page]).per(PER).order("created_at DESC")
    end
    render "search"
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def show
  end

  def new
  end

  def create
    @playlist = current_user.playlists.new(playlist_params)
    @playlist.tags.build(params[:tag][:content].split(",").uniq.map { |e| {content: e} })
    if @playlist.save
      redirect_to root_path, notice: "Added your playlist!"
    else
      redirect_to root_path, alert: "Add failed!"
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
    @playlists = Playlist.all.page(params[:page]).per(9)
    respond_to :js
  end

  private
    def playlist_params
      params.require(:playlist).permit(:content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
  end

  def destroy
    @id = params[:id]
    @tag = Tag.find(@id)
    @tag.destroy
    respond_to :js
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  PER = 6

  def show
    @user = User.find(params[:id])
    @playlists = @user.playlists.page(params[:page]).per(PER).order("created_at")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user.image
      user.image
    else
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
    end
  end

  def display_favorite(playlist)
    result = ''
    if current_user.favorite?(playlist)
      result = 'no-display'
    end
    result
  end

  def display_unfavorite(playlist)
    result = ''
    unless current_user.favorite?(playlist)
      result = 'no-display'
    end
    result
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/favorites/create.js.erb
$("#playlist_<%= @playlist.id %> .unfavorite").addClass("no-display");
$("#playlist_<%= @playlist.id %> .favorite").removeClass("no-display");

app/views/favorites/destroy.js.erb
$("#playlist_<%= @playlist.id %> .unfavorite").removeClass("no-display");
$("#playlist_<%= @playlist.id %> .favorite").addClass("no-display");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spolist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    
  </head>

  <body>

    <%= render "shared/navbar" %>
    <%= render "shared/message" %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<%= form_tag search_path, remote: true, method: :get do %>
  <div class="row mb-3">
    <div class="col-sm-9">
      <%= text_field_tag :search, params[:search], class: "form-control", id: "tag" %>
    </div>
    <div class="col-sm-3">
      <%= submit_tag "Search", class: "btn btn-normal btn-block" %>
    </div>
  </div>
<% end %>

<div id="playlists">
  <%= render partial: "playlists/playlist_list", locals: {playlists: @playlists} %>
</div>

app/views/pages/search.js.erb
$('#playlists').html("<%= j render partial: 'playlists/playlist_list', locals: {playlists: @playlists} %>")

app/views/playlists/_favorite_list.html.erb
<div class="row">
  <% playlists.each do |playlist| %>
    <div class="col-md-4">
      <div class="card card-playlist mb-2" id="playlist_<%= playlist.id %>">
        <div class="card-header">
          <%= link_to user_path(playlist.user) do %>
            <%= image_tag avatar_url(playlist.user), class: "rounded-circle avatar-small" %>
            <%= playlist.user.name %>
          <% end %>
          <% if user_signed_in? %>
            <%= link_to favorites_path({playlist_id: playlist.id}), remote: true, method: :post do %>
              <%= fa_icon "heart", class: "float-right unfavorite #{display_favorite(playlist)}" %>
            <% end %>
            <%= link_to favorite_path(playlist), remote: true, method: :delete do %>
              <%= fa_icon "heart", class: "float-right favorite #{display_unfavorite(playlist)}" %>
            <% end %>
            <%= link_to playlist_path(playlist), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
              <%= fa_icon "trash", class: "float-right" if current_user == playlist.user %>
            <% end %>
          <% end %>
        </div>
        <div class="card-body">
          <iframe src="https://open.spotify.com/embed/user/spotify/playlist/<%= playlist.content %>" class="frame-playlist" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
        </div>
        <div class="card-footer">
            <% playlist.tags.each do |tag| %>
              <span class="tag" id="tag_<%=tag.id %>">
                <%= tag.content %>
                <%= link_to tag_path(tag), remote: true, method: :delete do %>
                  <%= fa_icon "times" if current_user == playlist.user %>
                <% end %>
              </span>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="playlist-pagenate">
  <%= paginate playlists %>
</div>

app/views/playlists/_playlist_form.html.erb
<!-- Button to Open the Modal -->
<button type="button" class="btn btn-form btn-small" id="add_playlist_button" data-toggle="modal" data-target="#myModal">
  Add Your Playlist
</button>

<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Add Your Playlist</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <%= form_for  (playlist = current_user.playlists.build) do |f| %>
          <div class="form-group text-center">
            <%= f.text_area :content, rows: 3,placeholder: "playlist id", class: "form-control" %>
          </div>
          <%= fields_for playlist.tags.build do |tag| %>
            <div class="form-group text-center">
              <%= tag.text_field :content, placeholder: "ex) edm,american,woman", class: "form-control" %>
            </div>
          <% end %>
          <div class="text-center">
            <%= f.submit "Add Playlist", class: "btn btn-normal" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/playlists/_playlist_list.html.erb
<div class="row">
  <% playlists.each do |playlist| %>
    <div class="col-md-6 col-xl-4">
      <div class="card card-playlist mb-5" id="playlist_<%= playlist.id %>">
        <div class="card-header">
          <%= link_to user_path(playlist.user) do %>
            <%= image_tag avatar_url(playlist.user), class: "rounded-circle avatar-small" %>
            <%= playlist.user.name %>
          <% end %>
          <% if user_signed_in? %>
            <%= link_to favorites_path({playlist_id: playlist.id}), remote: true, method: :post do %>
              <%= fa_icon "heart", class: "float-right unfavorite #{display_favorite(playlist)}" unless current_user == playlist.user %>
            <% end %>
            <%= link_to favorite_path(playlist), remote: true, method: :delete do %>
              <%= fa_icon "heart", class: "float-right favorite #{display_unfavorite(playlist)}" unless current_user == playlist.user %>
            <% end %>
            <%= link_to playlist_path(playlist), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
              <%= fa_icon "trash", class: "float-right" if current_user == playlist.user %>
            <% end %>
          <% end %>
        </div>
        <div class="card-body">
          <iframe src="https://open.spotify.com/embed/user/spotify/playlist/<%= playlist.content %>" class="frame-playlist" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
        </div>
        <div class="card-footer">
            <% playlist.tags.each do |tag| %>
              <span class="tag" id="tag_<%=tag.id %>">
                <%= tag.content %>
                <%= link_to tag_path(tag), remote: true, method: :delete do %>
                  <%= fa_icon "times" if current_user == playlist.user %>
                <% end %>
              </span>
            <% end %>
            <span class="">
              <%= fa_icon "plus", class: "tag float-right" if current_user == playlist.user %>
            </span>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="playlist-pagenate">
  <%= paginate playlists %>
</div>

app/views/playlists/destroy.js.erb
$('#playlists').html("<%= j render partial: 'playlists/playlist_list', locals: {playlists: @playlists} %>")

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error("<%= value %>")
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub("alert", "error").gsub("notice", "success") %>
      toastr["<%= type %>"]("<%= value %>")
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-default mb-4 fixed-top">
  <div class="container">
    <%= link_to "SPOLIST", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if !user_signed_in? %>
          <li class="nav-item">
            <button class="btn btn-form btn-small" id="add_playlist_button">
              <%= link_to "Add Playlist", new_user_session_path, style: "color: white;, text-decoration: none;" %>
            </button>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item mr-2">
            <div>
              <%= render partial: "playlists/playlist_form", style: "color: white;, text-decoration: none;" %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "rounded-circle avatar-small" %>
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Your Playlist", user_path(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tags/destroy.js.erb
$('#tag_<%= @id %>').remove()

app/views/users/show.html.erb
<div class="row mb-3">
  <div class="col-md-3">
    <div class="center">
      <%= image_tag avatar_url(@user), class: "avatar-full" %>
    </div>
    <div class="card">
      <div class="card-header"><%= @user.name %></div>
      <div class="card-body">
        <%= @user.description || "no description" %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="description row-space-3">
    </div>
  </div>
</div>
<hr/>
<div id="playlists">
  <h2>Your Playlists</h2>
  <%= render partial: "playlists/playlist_list", locals: {playlists: @playlists} %>
</div>
<hr/>
<div id="favoritelists">
  <h2>Your Favorite Playlists</h2>
  <%= render partial: "playlists/playlist_list", locals: {playlists: current_user.favorite_playlists.page(params[:page]).per(6)} %>
</div>